### ISSUE TITLE
UserIntentions_CODE.xml

### ISSUE THREAD

**Issue by wahello** [mwierszycki/Abaqus-in-Apptainer-Singularity-container#1]
How to get [UserIntentions_CODE.xml](https://help.3ds.com/2024/english/dssimulia_established/estiinstallmap/esti-t-autosilentinstallersuite.htm?contextscope=all)?

**Comment by mwierszycki** [comment]
Hi, click the link, check the Abaqus documentation and follow the instruction. Briefly, you must run installer once, as a trial run, then retrieve the UserIntentions_CODE.xml file that is generated from the run. Regards, Marcin

**Comment by wahello** [comment]
Yes. In a simple and plain express: Just start GUI Installer and finish the whole installation procedure,  then a UserIntentions_xxx.xml file is generated in directory /tmp.
